package br.com.accesstage.trustion.client.cartoes.pci.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.4
 * Generated source version: 2.1
 */
@WebService(name = "KeysManagerWS", targetNamespace = "http://ws.pci.acesstage.com.br")
@XmlSeeAlso({ ObjectFactory.class })
public interface KeysManagerWS {

    /**
     * @param text
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "encryptReturn", targetNamespace = "http://ws.pci.acesstage.com.br")
    @RequestWrapper(localName = "encrypt", targetNamespace = "http://ws.pci.acesstage.com.br", className = "br.com.acesstage.pci.ws.Encrypt")
    @ResponseWrapper(localName = "encryptResponse", targetNamespace = "http://ws.pci.acesstage.com.br", className = "br.com.acesstage.pci.ws.EncryptResponse")
    public String encrypt(@WebParam(name = "text", targetNamespace = "http://ws.pci.acesstage.com.br") String text);

    /**
     * @param text
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "decryptReturn", targetNamespace = "http://ws.pci.acesstage.com.br")
    @RequestWrapper(localName = "decrypt", targetNamespace = "http://ws.pci.acesstage.com.br", className = "br.com.acesstage.pci.ws.Decrypt")
    @ResponseWrapper(localName = "decryptResponse", targetNamespace = "http://ws.pci.acesstage.com.br", className = "br.com.acesstage.pci.ws.DecryptResponse")
    public String decrypt(@WebParam(name = "text", targetNamespace = "http://ws.pci.acesstage.com.br") String text);

}
