---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      provider: accesstage
      project: trustion-servicos
      version: 0.0.1-SNAPSHOT
      group: br.com.accesstage
    name: trustion-servicos
    namespace: l2-backend-brinks
  spec:
    ports:
    - nodePort: 30986
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      project: trustion-servicos
      provider: accesstage
      group: br.com.accesstage
    type: NodePort
