package br.com.accesstage.trustion.repository.constantes;

public final class ConstantesConciliacaoCartao {

    public static final String QUERY_BUSCAR_REGISTROS_RESUMIDOS_CONCILIADOS
            = //queryBuscarRegistrosResumidosConciliados
            "SELECT "
            + "COD_OPERADORA, NME_EXIBICAO_PORTAL, DTA_EXTR_PAGAMENTO, COD_BANCO, COD_AGENCIA, COD_CONTA, "
            + "SUM(VLR_EXTR_TOTAL) AS VLR_EXTR_TOTAL, SUM(VLR_PGTO_TOTAL) AS VLR_PGTO_TOTAL, STA_CONCILIADO "
            + "FROM ( ";

    public static final String QUERY_BUSCAR_VALORES_EXTRATO_RESUMIDO_NAO_CONCILIADO = "SELECT A.COD_OPERADORA, "
            + "B.NME_EXIBICAO_PORTAL, TO_CHAR(A.DTA_EXTR_PAGAMENTO,'MM/YYYY') AS DTA_EXTR_PAGAMENTO, "
            + "C.NRO_BANCO AS COD_BANCO, C.NRO_AGENCIA AS COD_AGENCIA, C.NRO_CONTA_CORRENTE AS COD_CONTA, "
            + " A.STA_CONCILIADO, "
            + "SUM(A.VLR_EXTR_TOTAL) AS VLR_EXTR_TOTAL "
            + "FROM FIN_CONTABIL A, ADM_OPERADORA B, DIM_CONTA_BANCO C "
            + "WHERE B.COD_OPERADORA = A.COD_OPERADORA (+) "
            + "AND A.COD_CONTA_BANCO = C.COD_CONTA_BANCO "
            + "AND C.STA_ATIVO = 'SIM' "
            + "AND A.COD_EMPRESA = ? ";

    public static final String QUERY_BUSCAR_VALOR_CARTAO_RESUMIDO_NAO_CONCILIADO = "SELECT A.COD_OPERADORA, "
            + "B.NME_EXIBICAO_PORTAL, SUBSTRB(A.COD_DATA_CREDITO, 1, 6) AS DTA_EXTR_PAGAMENTO, "
            + "C.NRO_BANCO AS COD_BANCO, C.NRO_AGENCIA AS COD_AGENCIA, C.NRO_CONTA_CORRENTE AS COD_CONTA, "
            + "A.STA_CONCILIADO, "
            + "SUM(A.VLR_LIQUIDO) AS VLR_PGTO_TOTAL "
            + "FROM FATO_TRANSACAO_SUM A, ADM_OPERADORA B, DIM_CONTA_BANCO C "
            + "WHERE B.COD_OPERADORA = A.COD_OPERADORA (+) "
            + "AND A.COD_CONTA_BANCO = C.COD_CONTA_BANCO "
            + "AND C.STA_ATIVO = 'SIM' "
            + "AND A.EMPID = ? "
            + "AND A.COD_STATUS IN (3, 4, 6, 7, 8)";

    public static final String QUERY_BUSCAR_REGISTROS_EXTRATO_RESUMIDO_NAO_CONCILIADO = "SELECT A.COD_OPERADORA, "
            + "B.NME_EXIBICAO_PORTAL, TO_CHAR(A.DTA_EXTR_PAGAMENTO,'MM/YYYY') AS DTA_EXTR_PAGAMENTO , "
            + "D.NRO_BANCO AS COD_BANCO, D.NRO_AGENCIA AS COD_AGENCIA, D.NRO_CONTA_CORRENTE AS COD_CONTA, "
            + "SUM(C.VLR_LIQUIDO) AS VLR_PGTO_TOTAL, SUM(A.VLR_EXTR_TOTAL) AS VLR_EXTR_TOTAL, "
            + "A.STA_CONCILIADO "
            + "FROM FIN_CONTABIL A, ADM_OPERADORA B, FATO_TRANSACAO_SUM C, DIM_CONTA_BANCO D "
            + "WHERE B.COD_OPERADORA = A.COD_OPERADORA (+) "
            + "AND A.COD_CONTA_BANCO = D.COD_CONTA_BANCO "
            + "AND D.STA_ATIVO = 'SIM' "
            + "AND C.STA_CONCILIADO = 'N' "
            + "AND A.COD_EMPRESA = ? "
            + "AND C.COD_STATUS IN (3, 4, 6, 7, 8)";

    public static final String QUERY_BUSCAR_REGISTROS_EXTRATO_CONCILIADOS
            = "SELECT '1' AS COD_MOVIMENTO, "
            + "A.ID_FIN_CONTABIL, A.NRO_GRUPO_CONCILIADO, A.COD_EMPRESA, A.TPO_CONCILIACAO, "
            + "A.COD_OPERADORA, B.NME_EXIBICAO_PORTAL, A.DTA_EXTR_PAGAMENTO, A.STA_CONCILIACAO, A.NME_ARQUIVO AS NME_ARQUIVO_ORIGEM, "
            + "D.NRO_BANCO AS COD_BANCO, D.NRO_AGENCIA AS COD_AGENCIA, D.NRO_CONTA_CORRENTE AS COD_CONTA, "
            + "A.VLR_EXTR_TOTAL, C.NME_PRODUTO, A.DSC_EXTR_HISTORICO, A.DSC_EXTR_DOCUMENTO "
            + "FROM FIN_CONTABIL A, ADM_OPERADORA B, ADM_PRODUTO C, DIM_CONTA_BANCO D "
            + "WHERE B.COD_OPERADORA = A.COD_OPERADORA (+) "
            + "AND A.COD_PRODUTO = C.COD_PRODUTO "
            + "AND A.COD_CONTA_BANCO = D.COD_CONTA_BANCO "
            + "AND D.STA_ATIVO = 'SIM' "
            + "AND A.COD_EMPRESA = ? ";

    public static final String QUERY_BUSCAR_REGISTROS_CARTAO_CONCILIADO
            = "SELECT '2' AS COD_MOVIMENTO, "
            + "A.ID_FATO_TRANSACAO_SUM, A.NRO_GRUPO_CONCILIADO, A.EMPID, A.COD_OPERADORA, C.NME_PRODUTO, A.TPO_CONCILIADO, "
            + "A.VLR_LIQUIDO, A.COD_DATA_CREDITO, A.HASH_VALUE, B.NME_EXIBICAO_PORTAL, "
            + "A.COD_BANCO, A.COD_AGENCIA, A.COD_CONTA, "
            + "A.STA_CONCILIADO, A.STA_CONCILIACAO, A.NME_ARQUIVO_ORIGEM "
            + "FROM FATO_TRANSACAO_SUM A, ADM_OPERADORA B, ADM_PRODUTO C, DIM_CONTA_BANCO D "
            + "WHERE B.COD_OPERADORA = A.COD_OPERADORA (+) "
            + "AND A.COD_PRODUTO = C.COD_PRODUTO "
            + "AND A.COD_CONTA_BANCO = D.COD_CONTA_BANCO "
            + "AND D.STA_ATIVO = 'SIM' "
            + "AND A.EMPID = ? "
            + "AND A.COD_STATUS IN (3, 4, 6, 7, 8)";

    public static final String QUERY_BUSCAR_REGISTROS_EXTRATO_NAO_CONCILIADOS = "SELECT '1' AS COD_MOVIMENTO, "
            + "A.ID_FIN_CONTABIL, A.COD_EMPRESA, A.NRO_GRUPO_CONCILIADO, A.COD_CONTA_BANCO, A.TPO_CONCILIACAO, "
            + "A.COD_OPERADORA, B.NME_EXIBICAO_PORTAL, C.NME_PRODUTO, A.DTA_EXTR_PAGAMENTO, A.STA_CONCILIACAO, "
            + "A.COD_EXTR_BANCO AS COD_BANCO, A.COD_EXTR_AGENCIA AS COD_AGENCIA, A.COD_EXTR_CONTA AS COD_CONTA, "
            + "A.VLR_EXTR_TOTAL, A.NME_ARQUIVO AS NME_ARQUIVO_ORIGEM, A.DSC_EXTR_HISTORICO, A.DSC_EXTR_DOCUMENTO "
            + "FROM FIN_CONTABIL A, ADM_OPERADORA B, ADM_PRODUTO C, DIM_CONTA_BANCO D "
            + "WHERE B.COD_OPERADORA = A.COD_OPERADORA (+) "
            + "AND A.COD_PRODUTO = C.COD_PRODUTO "
            + "AND A.COD_CONTA_BANCO = D.COD_CONTA_BANCO "
            + "AND D.STA_ATIVO = 'SIM' "
            + "AND A.COD_EMPRESA = ?";

    public static final String QUERY_BUSCAR_REGISTROS_CARTAO_NAO_CONCILIADOS = "SELECT '2' AS COD_MOVIMENTO, "
            + "A.ID_FATO_TRANSACAO_SUM, A.EMPID, A.NRO_GRUPO_CONCILIADO, A.COD_OPERADORA, C.NME_PRODUTO, A.TPO_CONCILIADO, "
            + "A.VLR_LIQUIDO, TO_DATE(A.COD_DATA_CREDITO,'YYYYMMDD') AS COD_DATA_CREDITO, A.HASH_VALUE, "
            + "B.NME_OPERADORA, A.COD_BANCO, A.COD_AGENCIA, A.COD_CONTA, "
            + "A.STA_CONCILIADO, A.STA_CONCILIACAO, A.NME_ARQUIVO_ORIGEM "
            + "FROM FATO_TRANSACAO_SUM A, ADM_OPERADORA B, ADM_PRODUTO C, DIM_CONTA_BANCO D "
            + "WHERE B.COD_OPERADORA = A.COD_OPERADORA (+) "
            + "AND A.COD_PRODUTO = C.COD_PRODUTO "
            + "AND A.COD_CONTA_BANCO = D.COD_CONTA_BANCO "
            + "AND D.STA_ATIVO = 'SIM' "
            + "AND A.EMPID = ? "
            + "AND A.COD_STATUS IN (3, 4, 6, 7, 8)";

    public static final String QUERY_OBTER_EXTRATO_POR_ID = "SELECT '1' AS COD_MOVIMENTO, "
            + "A.ID_FIN_CONTABIL, A.NRO_GRUPO_CONCILIADO, A.COD_EMPRESA, A.TPO_CONCILIACAO, "
            + "A.COD_OPERADORA, B.NME_EXIBICAO_PORTAL, A.DTA_EXTR_PAGAMENTO, A.STA_CONCILIACAO, "
            + "A.COD_EXTR_BANCO AS COD_BANCO, A.COD_EXTR_AGENCIA AS COD_AGENCIA, A.COD_EXTR_CONTA AS COD_CONTA, "
            + "A.VLR_EXTR_TOTAL, A.NME_ARQUIVO AS NME_ARQUIVO_ORIGEM, C.NME_PRODUTO, A.DSC_EXTR_HISTORICO, A.DSC_EXTR_DOCUMENTO "
            + "FROM FIN_CONTABIL A, ADM_OPERADORA B, ADM_PRODUTO C "
            + "WHERE B.COD_OPERADORA = A.COD_OPERADORA (+) "
            + "AND A.COD_PRODUTO = C.COD_PRODUTO "
            + "AND A.COD_EMPRESA = ? "
            + "AND A.NRO_GRUPO_CONCILIADO = ? ";

    public static final String QUERY_OBTER_CARTAO_POR_ID = "SELECT '2' AS COD_MOVIMENTO, "
            + "A.ID_FATO_TRANSACAO_SUM, A.NRO_GRUPO_CONCILIADO, A.EMPID, A.COD_OPERADORA, A.TPO_CONCILIADO, A.VLR_LIQUIDO AS VLR_LIQUIDO, A.COD_DATA_CREDITO, A.HASH_VALUE, "
            + "B.NME_EXIBICAO_PORTAL, "
            + "A.COD_BANCO, A.COD_AGENCIA, A.COD_CONTA, A.STA_CONCILIADO, A.STA_CONCILIACAO, A.NME_ARQUIVO_ORIGEM, C.NME_PRODUTO "
            + "FROM FATO_TRANSACAO_SUM A, ADM_OPERADORA B, ADM_PRODUTO C "
            + "WHERE B.COD_OPERADORA = A.COD_OPERADORA (+) "
            + "AND A.COD_PRODUTO = C.COD_PRODUTO "
            + "AND A.EMPID = ? "
            + "AND A.NRO_GRUPO_CONCILIADO = ? "
            + "AND A.COD_STATUS IN (3, 4, 6, 7, 8) ";

    public static final String UPDATE_REGISTRO_EXTRATO = "UPDATE FIN_CONTABIL SET "
            + "STA_CONCILIADO = ?, STA_CONCILIACAO = ?, DTA_CONCILIADO = ?, TPO_CONCILIACAO = ?, STA_PREPROC = ?, MTV_CONCILIADO = ?, NRO_GRUPO_CONCILIADO = ? WHERE ID_FIN_CONTABIL = ?";

    public static final String UPDATE_REGISTRO_CARTAO = "UPDATE FATO_TRANSACAO_SUM SET "
            + "STA_CONCILIADO = ?, STA_CONCILIACAO = ?, DTA_CONCILIADO = ?, TPO_CONCILIADO = ?, STA_PREPROC = ?, NRO_GRUPO_CONCILIADO = ? WHERE HASH_VALUE = ?";

    public static final String QUERY_PESQUISA_TODOS_CLIENTE_ADQUIRENTE = "SELECT "
            + "NME_EXIBICAO_PORTAL, COD_OPERADORA "
            + "FROM ADM_OPERADORA ORDER BY NME_EXIBICAO_PORTAL";

    public static final String QUERY_PESQUISA_REGRA_CLIENTE_ADQUIRENTE = "SELECT "
            + "FIN.COD_BANCO, FIN.COD_OPERADORA, OPE.NME_EXIBICAO_PORTAL, FIN.EMPID, FIN.DSC_CHAVE_PRINCIPAL, FIN.DSC_CHAVE_SECUNDARIA, FIN.STA_ATIVO "
            + "FROM FIN_REGRA_EMPRESA FIN, ADM_OPERADORA OPE "
            + "WHERE FIN.COD_OPERADORA = OPE.COD_OPERADORA "
            + "AND FIN.EMPID = ? ";

    public static final String SELECT_ID_REGISTRO_CONCILIADO = "SELECT GRUPO_CONCILIADO_SEQ.NEXTVAL FROM DUAL ";

    private ConstantesConciliacaoCartao() {
        throw new IllegalAccessError("Utility class");
    }

}
